### ISSUE TITLE
验证计划

### ISSUE THREAD

**Issue by GGGitBoy** [GGGitBoy/test#1]
序号 | 验证目标 | 配置依赖 | 验证方法 | 命令 / 工具 | 预期结果
-- | -- | -- | -- | -- | --
1 | 验证服务间 mTLS 是否开启 | PeerAuthentication (STRICT / PERMISSIVE) | 从 Pod A 访问 Pod B 的服务 | kubectl exec pod-a -- curl http://pod-b:8080 | mTLS 开启时非 sidecar 请求被拒绝，sidecar 请求成功
2 | 验证 PERMISSIVE 模式兼容性 | PeerAuthentication PERMISSIVE | Pod A（sidecar）和 Pod B（无 sidecar）互访 | kubectl exec pod-a -- curl pod-b:8080 | 有 sidecar 的流量使用 mTLS，无 sidecar 的流量明文通过
3 | 验证 PeerAuthentication STRICT 模式 | PeerAuthentication STRICT | 无 sidecar Pod 尝试访问目标 Pod | kubectl exec pod-nonsidecar -- curl pod-b:8080 | 请求失败，连接被拒绝
4 | 验证 RequestAuthentication JWT 校验 | RequestAuthentication | 发送有效/无效 JWT 请求服务 | curl -H "x-jwt-assertion: Bearer <token>" http://service | 有效 token 通过，无效 token 不会拒绝请求（需 AuthorizationPolicy 配合）
5 | 验证 AuthorizationPolicy 限制访问 | AuthorizationPolicy | 从 Pod A 请求服务 | kubectl exec pod-a -- curl http://service | 策略允许的请求通过，禁止的请求返回 403
6 | 验证流量隔离 | DestinationRule + VirtualService | 不同版本 Pod 间访问 | curl http://v1-service / curl http://v2-service | Pod 只能访问允许的 subset，不在白名单的访问失败
7 | 验证外部服务访问控制 | ServiceEntry + PeerAuthentication | 外部请求访问内部服务 | curl http://service 从外部访问 | 如果策略禁止外部访问，请求被拒绝
8 | 验证 sidecar 注入 | Namespace label 或 istio-injection=enabled | 检查 Pod 是否注入 sidecar | `kubectl get pod -o yaml | grep istio-proxy`
9 | 验证跨 namespace 微隔离 | PeerAuthentication namespace scoped | Pod A (ns1) 请求 Pod B (ns2) | kubectl exec pod-a -n ns1 -- curl pod-b.ns2.svc.cluster.local | 根据 PeerAuthentication 设置，允许或拒绝跨 namespace 访问
10 | 验证日志与监控 | Istio Telemetry / Kiali | 访问服务，查看 mTLS 与授权日志 | Kiali / Grafana / istioctl authn tls-check | 日志显示流量加密状态和授权决策

**Comment by GGGitBoy** [comment]
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: ratings
spec:
  host: ratings
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: details
spec:
  host: details
  subsets:
  - name: v1
    labels:
      version: v1
```

**Comment by GGGitBoy** [comment]
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - productpage
  http:
  - route:
    - destination:
        host: productpage
        subset: v1
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - route:
    - destination:
        host: ratings
        subset: v1
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details
  http:
  - route:
    - destination:
        host: details
        subset: v1
---
```
